# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItN1pLigCsbOOrhZNYGwwY8Os3mn0P-j
"""

# master_data is the dataframe we get after data_ingestion gets executed


for column in master_data.columns:
    first_valid_idx = master_data[column].first_valid_index()  # Get the index of first non-null value
    if first_valid_idx is not None:
        master_data[column].loc[:first_valid_idx] = master_data[column].loc[:first_valid_idx].fillna(0)  # Fill initial NaNs with 0

columns_to_interpolate = master_data.columns[master_data.isnull().any()].tolist()

for column in columns_to_interpolate:
    master_data[column] = master_data[column].interpolate(method='linear', limit_direction='both', inplace=False)


  #get all columns that has generation data
import re

col_names_all = master_data.columns
col_gen_pattern = '_B'
col_gen = list() #store names of columns having generated data
for c in col_names_all:
  match = re.search(col_gen_pattern, c)
  if match:
    col_gen.append(c)

#group generation columns of each country
country_codes = {
'SP' : 0, # Spain
'UK' : 1, # United Kingdom
'DE' : 2, # Germany
'DK' : 3, # Denmark
'HU' : 5, # Hungary
'SE' : 4, # Sweden
'IT' : 6, # Italy
'PO' : 7, # Poland
'NE' : 8 # Netherlands
                 }

country_keys = list(country_codes)

gen_in_each_country = list()
for c1 in country_keys :
  col_subset = list()
  for cn1 in col_gen:
        match1 = re.search(c1, cn1)
        if match1:
          col_subset.append(cn1)
  if len(col_subset):
      gen_in_each_country.append(col_subset)

for i in country_keys:
  for j in gen_in_each_country:
    country_considered = j[0][:2]
    if (i == country_considered):
        # print(country_considered)
        if len(j) > 1:
          master_data[country_considered+"_gen"] = 0
          for k in j:
            master_data[country_considered+"_gen"] =  master_data[country_considered+"_gen"] + master_data[k]
        else:
          master_data[country_considered+"_gen"] = 0
          master_data[country_considered+"_gen"] = master_data[j[0]]


columns_to_select = ['StartTime_new', 'DE','DK', 'HU', 'IT', 'NE', 'PO', 'SE', 'SP', 'UK', 'SP_gen','UK_gen', 'DE_gen', 'DK_gen', 'HU_gen', 'SE_gen', 'IT_gen', 'PO_gen', 'NE_gen']
selected_columns_df1 = master_data[columns_to_select]
# final_columns - has the complete dataset we need to proceed further after interpolation of missing values
final_columns = pd.DataFrame()

for col in columns_to_select:
    final_columns[col] = selected_columns_df1[col]

# final_columns is the final dataframe we get after interpolation of missing values and addition of 0s . This dataframe will be further used for modelling